<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-16FT4HA3" failures="1" tests="1" name="LoginTest" time="5.552" errors="0" timestamp="2025-04-04T18:38:42 IST">
  <testcase classname="com.demoblaze.tests.LoginTest" name="validLoginTest" time="2.477">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.demoblaze.tests.LoginTest.validLoginTest(LoginTest.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- validLoginTest -->
</testsuite> <!-- LoginTest -->
